basePath: /api/v1
definitions:
  controller.ForgotPassword.userEmailReq:
    properties:
      email:
        maxLength: 150
        type: string
    required:
    - email
    type: object
  controller.UpdatePassword.userPassword:
    properties:
      password:
        maxLength: 50
        minLength: 8
        type: string
    required:
    - password
    type: object
  models.CreateUser:
    properties:
      email:
        maxLength: 150
        type: string
      firstName:
        maxLength: 50
        type: string
      identifier:
        maxLength: 100
        type: string
      lastName:
        maxLength: 50
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
      phoneNumber:
        type: string
    required:
    - email
    - firstName
    - identifier
    - lastName
    - password
    - phoneNumber
    type: object
  models.ErrorResponse:
    properties:
      errors: {}
      msg:
        type: string
    type: object
  models.UpdateUser:
    properties:
      avatar:
        type: string
      email:
        maxLength: 150
        type: string
      firstName:
        maxLength: 50
        type: string
      lastName:
        maxLength: 50
        type: string
      phoneNumber:
        type: string
    required:
    - email
    - firstName
    - lastName
    - phoneNumber
    type: object
  models.User:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      identifier:
        type: string
      lastName:
        type: string
      phoneNumber:
        type: string
      updatedAt:
        type: string
    type: object
  models.UserLogin:
    properties:
      identifier:
        maxLength: 100
        type: string
      password:
        maxLength: 50
        minLength: 8
        type: string
    required:
    - identifier
    - password
    type: object
  models.UserToken:
    properties:
      access_Token:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: tringuyen2762001@gmail.com
    name: Nguyen Tri
  description: greendeco
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Fiber Go API
  version: "1.0"
paths:
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: send email to user for reset password
      parameters:
      - description: user email
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/controller.ForgotPassword.userEmailReq'
      responses:
        "200":
          description: OK
      summary: option when user forgot password
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Use for login response the access_Token
      parameters:
      - description: Login
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserToken'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "403":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: User Login
      tags:
      - Auth
  /auth/password:
    put:
      consumes:
      - application/json
      description: Update Password
      parameters:
      - description: Updated Password
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/controller.UpdatePassword.userPassword'
      responses:
        "204":
          description: No Content
      security:
      - Bearer: []
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: New User
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "403":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create new user
      tags:
      - Auth
  /media/upload:
    post:
      consumes:
      - multipart/form-data
      operationId: image
      parameters:
      - description: upfile
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
      security:
      - ApiKeyAuth: []
      summary: Create new image return image
  /user/me:
    get:
      consumes:
      - application/json
      description: route get user Id from token then get user information
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "403":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      security:
      - Bearer: []
      summary: get user information by Id
      tags:
      - User
  /user/update:
    put:
      consumes:
      - application/json
      description: update user information
      parameters:
      - description: Updated UserInformation
        in: body
        name: todo
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUser'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - Bearer: []
      tags:
      - User
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
